In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import SimpleRNN

In [2]:
train_X = [
           [0.1, 4.2, 1.5, 1.1, 2.8],
           [1.0, 3.1, 2.5, 0.7, 1.1],
           [0.3, 2.1, 1.5, 2.1, 0.1],
           [2.2, 1.4, 0.5, 0.9, 1.1]
]
train_X = np.array(train_X, dtype=np.float32)

print(np.shape(train_X))
print(train_X.shape)

(4, 5)
(4, 5)


In [3]:
train_X = [[
           [0.1, 4.2, 1.5, 1.1, 2.8],
           [1.0, 3.1, 2.5, 0.7, 1.1],
           [0.3, 2.1, 1.5, 2.1, 0.1],
           [2.2, 1.4, 0.5, 0.9, 1.1]
]]
train_X = np.array(train_X, dtype=np.float32)

print(train_X)
print(train_X.shape)

[[[0.1 4.2 1.5 1.1 2.8]
  [1.  3.1 2.5 0.7 1.1]
  [0.3 2.1 1.5 2.1 0.1]
  [2.2 1.4 0.5 0.9 1.1]]]
(1, 4, 5)


In [4]:
rnn = SimpleRNN(3, return_sequences=True, return_state=True)
rnn(train_X)
print(rnn(train_X)) # 마지막 레이어의 출력만 보여줌

[<tf.Tensor: shape=(1, 4, 3), dtype=float32, numpy=
array([[[-0.97051233,  0.04499815,  0.13997163],
        [-0.9051132 ,  0.45567435, -0.91906685],
        [-0.96244997, -0.49736175, -0.72133595],
        [-0.9071449 , -0.6732627 , -0.99065846]]], dtype=float32)>, <tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[-0.9071449 , -0.6732627 , -0.99065846]], dtype=float32)>]


In [5]:
hidden_states, last_states = rnn(train_X)
print('train_X : {}, shape: {}'.format(train_X, train_X.shape))
print('hidden states : {}, shape : {}'.format(hidden_states, hidden_states.shape))
print('last hidden state : {}, shape : {}'.format(last_states, last_states.shape))

train_X : [[[0.1 4.2 1.5 1.1 2.8]
  [1.  3.1 2.5 0.7 1.1]
  [0.3 2.1 1.5 2.1 0.1]
  [2.2 1.4 0.5 0.9 1.1]]], shape: (1, 4, 5)
hidden states : [[[-0.97051233  0.04499815  0.13997163]
  [-0.9051132   0.45567435 -0.91906685]
  [-0.96244997 -0.49736175 -0.72133595]
  [-0.9071449  -0.6732627  -0.99065846]]], shape : (1, 4, 3)
last hidden state : [[-0.9071449  -0.6732627  -0.99065846]], shape : (1, 3)


In [6]:
from tensorflow.keras.layers import SimpleRNN, Dense

rnn = SimpleRNN(3, return_sequences=True, return_state=True)
rnn = Dense(5, activation="softmax")

print(rnn(train_X))

tf.Tensor(
[[[0.00430828 0.02504233 0.00154475 0.9672008  0.00190382]
  [0.00469284 0.02168536 0.01550873 0.93123806 0.02687506]
  [0.04744295 0.03919011 0.0397533  0.8310337  0.04257994]
  [0.10434824 0.04434691 0.30306593 0.43922016 0.10901887]]], shape=(1, 4, 5), dtype=float32)


In [7]:
from keras_preprocessing.text import Tokenizer
text='이 여름 다시 한번 설레고 싶다 그 여름 틀어줘'
t = Tokenizer()
t.fit_on_texts([text])
encoded = t.texts_to_sequences([text])[0]

In [8]:
t.texts_to_sequences([text])

[[2, 1, 3, 4, 5, 6, 7, 1, 8]]

In [9]:
t.texts_to_sequences([text])[0]

[2, 1, 3, 4, 5, 6, 7, 1, 8]

In [10]:
vocab_size = len(t.word_index) + 1 # 단어의 개수는 8개지만 문장의 끝임을 알려주는 '\n'이 들어가야 되므로 +1 해준다? 
print('단어 집합의 크기 : ', vocab_size)

단어 집합의 크기 :  9


In [11]:
print(t.word_index)

{'여름': 1, '이': 2, '다시': 3, '한번': 4, '설레고': 5, '싶다': 6, '그': 7, '틀어줘': 8}


In [12]:
sequences = list()
for c in range(1,len(encoded)) :
  sequence = encoded[c-1:c+1]
  sequences.append(sequence)
print('단어 묶음의 개수:', len(sequences))
print(sequences)

단어 묶음의 개수: 8
[[2, 1], [1, 3], [3, 4], [4, 5], [5, 6], [6, 7], [7, 1], [1, 8]]


In [13]:
import numpy as np
X, y = zip(*sequences)
X = np.array(X)
y = np.array(y)

In [14]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y, num_classes=vocab_size)
print(y)

[[0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [15]:
from keras.layers import Embedding, Dense, SimpleRNN
from keras.models import Sequential

model = Sequential()
model.add(Embedding(vocab_size, 9, input_length=1))
model.add(SimpleRNN(9))
model.add(Dense(vocab_size, activation='softmax'))

In [16]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=500)

Epoch 1/500
1/1 [==============================] - 2s 2s/step - loss: 2.1954 - accuracy: 0.2500
Epoch 2/500
1/1 [==============================] - 0s 12ms/step - loss: 2.1919 - accuracy: 0.2500
Epoch 3/500
1/1 [==============================] - 0s 8ms/step - loss: 2.1885 - accuracy: 0.2500
Epoch 4/500
1/1 [==============================] - 0s 10ms/step - loss: 2.1851 - accuracy: 0.2500
Epoch 5/500
1/1 [==============================] - 0s 11ms/step - loss: 2.1817 - accuracy: 0.2500
Epoch 6/500
1/1 [==============================] - 0s 9ms/step - loss: 2.1783 - accuracy: 0.2500
Epoch 7/500
1/1 [==============================] - 0s 9ms/step - loss: 2.1749 - accuracy: 0.2500
Epoch 8/500
1/1 [==============================] - 0s 11ms/step - loss: 2.1715 - accuracy: 0.2500
Epoch 9/500
1/1 [==============================] - 0s 11ms/step - loss: 2.1681 - accuracy: 0.3750
Epoch 10/500
1/1 [==============================] - 0s 11ms/step - loss: 2.1648 - accuracy: 0.3750
Epoch 11/500
1/1 [======

In [17]:
print(t.word_index.items())

dict_items([('여름', 1), ('이', 2), ('다시', 3), ('한번', 4), ('설레고', 5), ('싶다', 6), ('그', 7), ('틀어줘', 8)])


In [18]:
def predict_next_word(model, t, current_word) :
  encoded = t.texts_to_sequences([current_word])[0]
  encoded = np.array(encoded)
  #result = model.predict_classes(encoded, verbose=0) #tf2.6 deprecated
  y_prob = model.predict(encoded, verbose=0)
  result = y_prob.argmax(axis=-1)
  for word, index in t.word_index.items() :
    if index == result :
      return word

In [19]:
print(predict_next_word(model, t, '다시'))

한번


In [20]:
print(predict_next_word(model, t, '틀어줘'))

싶다


In [21]:
def sentence_generation(model, t, current_word, n) :
  init_word = current_word
  sentence = ''
  for _ in range(n) :
    encoded = t.texts_to_sequences([current_word])[0]
    encoded = np.array(encoded)
    y_prob = model.predict(encoded, verbose=0)
    result = y_prob.argmax(axis=-1)
    for word, index in t.word_index.items() :
      if index == result :
        break
    current_word = word
    sentence = sentence + ' ' + word
  
  sentence = init_word + sentence
  return sentence

In [22]:
print(sentence_generation(model, t, '다시', 6))

다시 한번 설레고 싶다 그 여름 틀어줘


In [23]:
print(sentence_generation(model, t, '여름', 6))

여름 틀어줘 싶다 그 여름 틀어줘 싶다
